kind: Deployment
apiVersion: apps/v1
metadata:
  name: quiz-api-git-1
  generation: 3
  labels:
    app: quiz-api-git-1
    app.kubernetes.io/component: quiz-api-git-1
    app.kubernetes.io/instance: quiz-api-git-1
    app.kubernetes.io/name: quiz-api-git-1
    app.kubernetes.io/part-of: Triggers
    app.openshift.io/runtime: dotnet
    app.openshift.io/runtime-version: 7.0-ubi8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz-api-git-1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quiz-api-git-1
        deployment: quiz-api-git-1
    spec:
      containers:
        - name: quiz-api-git-1
          image: >-
            image-registry.openshift-image-registry.svc:5000/pipelines-quiz-api/quiz-api-git-1@sha256:ef5e3b7ffb9c075cd9eb4521af4a64f9747878691a1b397910c770b507f86653
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
