kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: quiz-api-git-1
  namespace: pipelines-quiz-api
  uid: 5fb9ad79-5977-4e74-83c6-8730c2c7f02e
  resourceVersion: '36144312'
  creationTimestamp: '2023-07-11T03:53:41Z'
  labels:
    app: quiz-api-git-1
    app.kubernetes.io/component: quiz-api-git-1
    app.kubernetes.io/instance: quiz-api-git-1
    app.kubernetes.io/name: quiz-api-git-1
    app.kubernetes.io/part-of: Triggers
    app.openshift.io/runtime: dotnet
    app.openshift.io/runtime-version: 7.0-ubi8
  annotations:
    openshift.io/host.generated: 'true'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2023-07-11T03:53:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:port':
            .: {}
            'f:targetPort': {}
          'f:tls':
            .: {}
            'f:insecureEdgeTerminationPolicy': {}
            'f:termination': {}
          'f:to':
            'f:kind': {}
            'f:name': {}
            'f:weight': {}
          'f:wildcardPolicy': {}
    - manager: openshift-router
      operation: Update
      apiVersion: route.openshift.io/v1
      time: '2023-07-11T03:53:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:ingress': {}
      subresource: status
spec:
  host: >-
    quiz-api-git-1-pipelines-quiz-api.apps.cluster-225g7.225g7.sandbox1786.opentlc.com
  to:
    kind: Service
    name: quiz-api-git-1
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
status:
  ingress:
    - host: >-
        quiz-api-git-1-pipelines-quiz-api.apps.cluster-225g7.225g7.sandbox1786.opentlc.com
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2023-07-11T03:53:41Z'
      wildcardPolicy: None
      routerCanonicalHostname: router-default.apps.cluster-225g7.225g7.sandbox1786.opentlc.com
