kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: quiz-client-git
  labels:
    app: quiz-client-git
    app.kubernetes.io/component: quiz-client-git
    app.kubernetes.io/instance: quiz-client-git
    app.kubernetes.io/name: quiz-client-git
    app.kubernetes.io/part-of: quiz-client-git-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
  annotations:
    openshift.io/host.generated: 'true'
  managedFields:
spec:
  host: >-
    quiz-client-git-pipelines-quiz-client.apps.cluster-225g7.225g7.sandbox1786.opentlc.com
  to:
    kind: Service
    name: quiz-client-git
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
