kind: Service
apiVersion: v1
metadata:
  name: quiz-api-git-1
  labels:
    app: quiz-api-git-1
    app.kubernetes.io/component: quiz-api-git-1
    app.kubernetes.io/instance: quiz-api-git-1
    app.kubernetes.io/name: quiz-api-git-1
    app.kubernetes.io/part-of: Triggers
    app.openshift.io/runtime: dotnet
    app.openshift.io/runtime-version: 7.0-ubi8
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/kirannreddy/quiz-api.git'
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: quiz-api-git-1
    deployment: quiz-api-git-1
